@startuml
skinparam classAttributeIconSize 0

class DatabaseConnectionPool {
	-dbOptions: Object
	-connectionPool: Object
	runQuery(sql, params): Object[] | Object
	close(): void
	getPool(): Object
	{static} validateQuery(sql, params): string
}

@enduml
